server:
  port: 8181
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
#openfeign底层还是由ribbon来做,所以超时时间由ribbon的参数决定
ribbon:
#  建立连接时间
  ReadTimeout:  5000
#  建立好连接之后,一次连接的持续时间
  ConnectTimeout: 5000
logging:
  level:
#    以什么级别监控那个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug


