server:
  port: 8182


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: order-hystrix-8182 #修改服务集群下的主机名
    prefer-ip-address: true
#openfeign底层还是由ribbon来做,所以超时时间由ribbon的参数决定


feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。


ribbon:
  #  建立连接的时间
  ReadTimeout:  3200
  #  连接持续时间
  ConnectTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
#  根据http响应码重试
  retryableStatusCodes: 404,502,408
spring:
  application:
    name: cloud-provider-hystrix-order

