server:
  port: 8001
#  自我保护
#  enable-self-preservation: false
#  eviction-interval-timer-in-ms: 2000

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql1234
  #    redis单机配置
  redis:
    host: localhost
    port: 6379  #可不配，因为底层默认值为6379
  #19527为后管端口,5672为访问端口
  rabbitmq:
    host: localhost
    port: 5672
    username: ems
    password: 123456
    virtual-host: /ems

#    redis集群配置
#  redis:
#    database: 0
#    pool:
#      max-active: 100 #连接池最大连接数（负值表示没有限制）
#      max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
#      max-idle: 200 #连接池最大空闭连接数
#      min-idle: 50 #连接汉最小空闲连接数
#      timeout: 600 #连接超时时间（毫秒）
#    cluster:
#      nodes:
#        - 192.168.75.132:6380
#        - 192.168.75.132:6381
#        - 192.168.75.132:6382
#        - 192.168.75.132:6383
#        - 192.168.75.132:6384
#        - 192.168.75.132:6385


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001 #修改服务集群下的主机名
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

mybatis-plus:
  #  config-location: classpath:mybatis-config.xml
  #  mapperLocations: classpath:mapper/*.xml
  #  type-aliases-package: com.atguigu.springcloud.entities
  global-config:
    db-config:
      #逻辑删除 全局字段名 添加之后不用添加@TableLogic
      logic-delete-field: deleted
      #逻辑删除,未删除的字段值 1
      logic-not-delete-value: 1
      #逻辑删除,已删除的字段值 0
      logic-delete-value: 0

xxl:
#  enable: false
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8888/xxl-job-admin
    executor:
      address:
      appname: xxl-job-executor-sample
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999


pagehelper:
  helper-dialect: mysql
  pageSizeZero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true