server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
#    client:
#      rm-report-success-enable: true
#      rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
#      rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
#      rm-async-commit-buffer-limit: 1000 # 异步提交缓存队列长度（默认10000）
#      rm:
#        lock:
#          lock-retry-internal: 10 # 校验或占用全局锁重试间隔（默认10ms）
#          lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
#          lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
#      tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
#      tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
#      undo:
#        undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
#        undo-log-serialization: jackson # undo序列化方式（默认jackson）
#        undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
#      log:
#        exceptionRate: 100 # 日志异常输出概率（默认100）
#      support:
#        spring-datasource-autoproxy: true # 数据源自动代理开关（默认false关闭）
#      service:
#        vgroup-mapping: default # TC 集群（必须与seata-server保持一致）
#        enable-degrade: false # 降级开关
#        disable-global-transaction: false # 禁用全局事务（默认false）
#      transport:
#        enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
#      registry:
#        type: eureka
#        eureka:
#          serviceUrl: ${eureka.host}
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: mysql1234
ribbon:
  #  建立连接的时间
  ReadTimeout:  32000
  #  连接持续时间
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  #  根据http响应码重试
  retryableStatusCodes: 404,502,408
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
